# Base Configuration File
system:
  name: "Financial Case Management Chatbot"
  version: "1.0.0"
  description: "Intelligent chatbot for financial case management"

api:
  host: ${API_HOST:-0.0.0.0}
  port: ${API_PORT:-8000}
  prefix: "/api/v1"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limit: 100
  timeout: 30

websocket:
  heartbeat_interval: 30
  max_connections: 1000
  message_size_limit: 1048576  # 1MB

llm_providers:
  # Primary LLM Provider - Eliza (Organization's custom gateway)
  eliza:
    enabled: true
    cert_path: ${ELIZA_CERT_PATH}
    private_key_path: ${ELIZA_PRIVATE_KEY_PATH}
    environment: ${ELIZA_ENV:-QA}
    default_model: ${ELIZA_DEFAULT_MODEL:-llama-3.3}
    timeout: ${ELIZA_TIMEOUT:-30}
    retry_attempts: ${ELIZA_RETRY_ATTEMPTS:-3}
    models:
      - llama-3.3
      - llama-3.1-70b

  # Alternative Provider - OpenAI
  openai:
    enabled: false  # Set to true to enable
    api_key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL:-gpt-4}
    base_url: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
    timeout: ${OPENAI_TIMEOUT:-60}
    max_retries: ${OPENAI_MAX_RETRIES:-3}
    organization_id: ${OPENAI_ORGANIZATION_ID}  # Optional
    models:
      - gpt-4
      - gpt-4-turbo-preview
      - gpt-3.5-turbo

  # Alternative Provider - Anthropic Claude
  anthropic:
    enabled: false  # Set to true to enable
    api_key: ${ANTHROPIC_API_KEY}
    model: ${ANTHROPIC_MODEL:-claude-3-sonnet-20240229}
    base_url: ${ANTHROPIC_BASE_URL:-https://api.anthropic.com/v1}
    timeout: ${ANTHROPIC_TIMEOUT:-60}
    max_retries: ${ANTHROPIC_MAX_RETRIES:-3}
    models:
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
      - claude-3-haiku-20240307

  # Unified Provider - LiteLLM (supports 100+ providers)
  litellm:
    enabled: false  # Set to true to enable
    api_key: ${LITELLM_API_KEY}
    model: ${LITELLM_MODEL:-gpt-3.5-turbo}
    base_url: ${LITELLM_BASE_URL}
    timeout: ${LITELLM_TIMEOUT:-60}
    max_retries: ${LITELLM_MAX_RETRIES:-3}

database:
  postgresql:
    host: ${POSTGRES_HOST:-localhost}
    port: ${POSTGRES_PORT:-5432}
    db: ${POSTGRES_DB:-chatbot_db}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool_size: 20
    pool_min: 5
    pool_max: 30

  oracle:
    host: ${ORACLE_HOST:-localhost}
    port: ${ORACLE_PORT:-1521}
    service_name: ${ORACLE_SERVICE_NAME:-ORCL}
    user: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    pool_min: 5
    pool_max: 20
    pool_increment: 2
    thin_mode: true

redis:
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  db: ${REDIS_DB:-0}
  password: ${REDIS_PASSWORD}
  ttl: 3600
  max_connections: 50

data_sources:
  - id: "customer_api"
    type: "rest"
    enabled: true
    config:
      base_url: ${EXTERNAL_API_BASE_URL}
      auth_type: "bearer"
      timeout: 30
      retry_attempts: 3
    capabilities:
      - "customer_data"
      - "account_info"
    semantic_descriptions:
      - "Retrieve customer information"
      - "Get account details and balances"

  - id: "case_database"
    type: "postgresql"
    enabled: true
    capabilities:
      - "case_management"
      - "case_history"
      - "case_status"
    semantic_descriptions:
      - "Query case information and status"
      - "Retrieve historical case data"
      - "Update case details"

logging:
  level: ${LOG_LEVEL:-INFO}
  format: "json"
  file: ${LOG_FILE:-/var/log/chatbot/app.log}
  max_size: "100MB"
  max_backups: 5

security:
  jwt_algorithm: "HS256"
  jwt_expiration_minutes: 60
  allowed_origins:
    - "http://localhost:3000"
  rate_limit:
    requests_per_minute: 100
    burst_size: 20